Custom XML attributes added
gelitenight/WaveView pull request #22
Opened 2018-09-03 20:40 UTC by wasabi-lee

Added the custom XML attributes so that the view components can be configured from XML directly.

2018-09-04 09:50 UTC, gelitenight requested changes
typedArray should be recycled after using

2018-09-04 09:50 UTC, gelitenight commented on library/src/main/java/com/gelitenight/waveview/library/WaveView.java
> +        mShowWave = typedArray.getBoolean(R.styleable.WaveView_showWave, true);
typedArray should be recycled after using

2018-09-05 19:19 UTC, wasabi-lee commented on library/src/main/java/com/gelitenight/waveview/library/WaveView.java
> +        typedArray.recycle();
Added the TypedArray.recycle()

2018-09-07 07:24 UTC, gelitenight approved these changes

2018-09-07 07:24 UTC, merged